`ifndef DEFINE_STATE

// This defines the states
typedef enum logic [2:0] {
	S_IDLE,
	S_ENABLE_UART_RX,
	S_WAIT_UART_RX,
	S_M1,
	S_M2
} top_state_type;

typedef enum logic [1:0] {
	S_RXC_IDLE,
	S_RXC_SYNC,
	S_RXC_ASSEMBLE_DATA,
	S_RXC_STOP_BIT
} RX_Controller_state_type;

typedef enum logic [2:0] {
	S_US_IDLE,
	S_US_STRIP_FILE_HEADER_1,
	S_US_STRIP_FILE_HEADER_2,
	S_US_START_FIRST_BYTE_RECEIVE,
	S_US_WRITE_FIRST_BYTE,
	S_US_START_SECOND_BYTE_RECEIVE,
	S_US_WRITE_SECOND_BYTE
} UART_SRAM_state_type;

typedef enum logic [3:0] {
	S_VS_WAIT_NEW_PIXEL_ROW,
	S_VS_NEW_PIXEL_ROW_DELAY_1,
	S_VS_NEW_PIXEL_ROW_DELAY_2,
	S_VS_NEW_PIXEL_ROW_DELAY_3,
	S_VS_NEW_PIXEL_ROW_DELAY_4,
	S_VS_NEW_PIXEL_ROW_DELAY_5,
	S_VS_FETCH_PIXEL_DATA_0,
	S_VS_FETCH_PIXEL_DATA_1,
	S_VS_FETCH_PIXEL_DATA_2,
	S_VS_FETCH_PIXEL_DATA_3
} VGA_SRAM_state_type;

typedef enum logic [5:0] {
    M1_IDLE,
	M1_LEAD_0,
	M1_LEAD_1,
	M1_LEAD_2,
	M1_LEAD_3,
	M1_LEAD_4,
	M1_LEAD_5,
	M1_LEAD_6,
	M1_LEAD_7,
	M1_LEAD_8,
	M1_LEAD_9,
	M1_LEAD_10,
	M1_COMMON_1,
	M1_COMMON_2,
	M1_COMMON_3,
	M1_COMMON_4,
	M1_COMMON_5,
	M1_COMMON_6,
	M1_COMMON_7,
	M1_COMMON_8,
	M1_COMMON_9,
	M1_COMMON_10,
	M1_COMMON_11,
	M1_COMMON_12,
	M1_OUT_1,
	M1_OUT_2,
	M1_OUT_3,
	M1_OUT_4,
	M1_OUT_5,
	M1_OUT_6,
	M1_OUT_7,
	M1_OUT_8,
	M1_OUT_9,
	M1_OUT_10,
	M1_OUT_11
} milestone1_state_type;

typedef enum logic [5:0] {
	
    M2_IDLE,
	M2_DELAY,
	SRAM_DELAY0,
	SRAM_DELAY1,
	SRAM_DELAY2,
	M2_FETCH0,
	M2_FETCH1,
	M2_FETCH2,
	M2_FETCH3,
	M2_FETCH4,
	M2_FETCH5,
	M2_FETCH6,
	M2_FETCH7,
	M2_FETCH8,
	M2_FETCH9,
	M2_COMPUTE_T_L0,
	M2_COMPUTE_T_L1,
	M2_COMPUTE_T0,
	M2_COMPUTE_T1,
	M2_COMPUTE_T2,
	M2_COMPUTE_T3,
	M2_COMPUTE_T4,
	M2_COMPUTE_T5,
	M2_COMPUTE_T6,
	M2_COMPUTE_T7,
	M2_COMPUTE_T8,
	M2_COMPUTE_T9,
	END,
	Lead1,
	Lead2,
	Mega1,
	Mega2,
	Mega3,
	Mega4,
	Mega5,
	Mega6,
	Mega7,
	Mega8,
	Mega9,
	Mega10,
	Mega11,
	Mega12,
	Mega13,
	Mega14,
	Mega15,
	Mega16,
	Mega17,
	Mega18,
	Mega19,
	Mega20,
	Mega21,
	Mega22,
	Mega23,
	Mega24,
	Mega25,
	LeadOut1,
	LeadOut2
	

} milestone2_state_type;

`define DEFINE_STATE 1
`endif
